/**
 * Generates src/data/imagery.ts from the live Palmonas/Demifine Shopify catalogue.
 *
 * Pulls first-party product photography and collection banner assets so the
 * prototype renders real brand imagery instead of generated placeholders.
 *
 * Run: node scripts/fetch-imagery.mjs
 */

import { writeFileSync } from "node:fs";

const STORE = "https://staging.demifine.com";
const UA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36";

const get = async (url) => {
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
};

// Strip Shopify cache-busting query so URLs stay stable and readable.
const clean = (src) => src.split("?")[0];

/**
 * The catalogue mixes two shoot types:
 *  - studio cut-outs on pure white (large, filenames like RGS0057-5-Y_00000)
 *  - lifestyle/model shots (1000px, filenames prefixed "Shopify_")
 * We want studio first and the model shot on hover, and we harvest the model
 * shots for editorial bands because they read as campaign photography.
 */
const isLifestyle = (src) => /\/Shopify_/i.test(src);

const CATEGORY_RULES = [
  { slug: "rings", types: ["Rings"], exclude: /bangle/i },
  { slug: "necklaces", types: ["Necklaces", "Mangalsutras"], exclude: null },
  { slug: "earrings", types: ["Earrings"], exclude: null },
  {
    slug: "bracelets",
    types: ["Bracelets", "Mangalsutra Bracelets"],
    exclude: /bangle|charm/i,
  },
  { slug: "bangles", types: null, include: /bangle/i },
  { slug: "charms", types: null, include: /charm/i },
];

async function main() {
  const pages = await Promise.all([
    get(`${STORE}/products.json?limit=250`),
    get(`${STORE}/products.json?limit=250&page=2`),
  ]);

  const seen = new Set();
  const products = pages
    .flatMap((p) => p.products)
    .filter((p) => !seen.has(p.id) && seen.add(p.id))
    .filter((p) => p.images?.length >= 1);

  const imagery = {};
  const used = new Set();
  const lifestylePool = [];

  for (const rule of CATEGORY_RULES) {
    const matches = products.filter((p) => {
      if (rule.include && !rule.include.test(p.title)) return false;
      if (rule.types && !rule.types.includes(p.product_type)) return false;
      if (rule.exclude && rule.exclude.test(p.title)) return false;
      return true;
    });

    const sets = [];
    for (const p of matches) {
      if (used.has(p.id)) continue;
      used.add(p.id);
      const srcs = p.images.map((i) => clean(i.src));
      const studio = srcs.filter((s) => !isLifestyle(s));
      const lifestyle = srcs.filter(isLifestyle);

      const primary = studio[0] ?? srcs[0];
      // Falls back to the primary shot when a piece has no second angle,
      // so the hover swap simply becomes a no-op rather than breaking.
      const hover = lifestyle[0] ?? studio[1] ?? primary;

      sets.push({
        primary,
        hover,
        extra: [...lifestyle.slice(1), ...studio.slice(1)].slice(0, 3),
      });
      lifestyle.forEach((s) => lifestylePool.push(s));
      if (sets.length >= 14) break;
    }
    imagery[rule.slug] = sets;
    console.log(`${rule.slug}: ${sets.length} image sets`);
  }

  /**
   * Editorial bands use model photography from the catalogue rather than the
   * store's collection artwork: those collection banners are 1700x500
   * marketing creatives with offer copy burnt into the pixels, which would
   * collide with our own headlines and undercut the positioning.
   */
  const banners = [...new Set(lifestylePool)];
  console.log(`editorial (model) images: ${banners.length}`);

  const at = (n) => banners[n % banners.length] ?? "";

  const banner = {
    hero: at(0),
    signature: at(1),
    craft: at(2),
    story: at(3),
    personalisation: at(4),
    collection: at(5),
  };

  const file = `/**
 * AUTO-GENERATED by scripts/fetch-imagery.mjs — do not edit by hand.
 *
 * First-party Palmonas / Demifine product photography and collection artwork.
 * Product shots are square (1:1) studio images; banners are landscape.
 */

import type { CategorySlug, ImageSet } from "@/types";

export type { ImageSet };

export const CATEGORY_IMAGERY: Record<CategorySlug, ImageSet[]> = ${JSON.stringify(imagery, null, 2)};

export const BANNERS = ${JSON.stringify(banner, null, 2)} as const;

export const ALL_BANNERS: string[] = ${JSON.stringify(banners.slice(0, 40), null, 2)};
`;

  writeFileSync(new URL("../src/data/generated/imagery.ts", import.meta.url), file);
  console.log("\nWrote src/data/generated/imagery.ts");
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
