/**
 * AUTO-GENERATED by scripts/fetch-imagery.mjs — do not edit by hand.
 *
 * First-party Palmonas / Demifine product photography and collection artwork.
 * Product shots are square (1:1) studio images; banners are landscape.
 */

import type { CategorySlug } from "@/types";

export type ImageSet = {
  primary: string;
  hover: string;
  extra: string[];
};

export const CATEGORY_IMAGERY: Record<CategorySlug, ImageSet[]> = {
  "rings": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0057-5-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_76039358-ad26-4547-9060-1aff85ac34c6.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_7b905e74-6e4b-4f39-b99e-d0b971c55e19.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ba08e1de-5486-44e9-8a71-2585f8d52771.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0057-5-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0056_Y_00001_2__compressed_56bd3648-4403-4da3-88ce-c12e193161bc.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_121eaebb-131c-49e9-b628-11e9dbdb16d3.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b0ed2fe1-e228-4c8e-b3da-8f47e15c12c6.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_a26ef832-ea5a-4ead-adf8-fe96f3d0e660.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0056_Y_00001_1__compressed_bfa0595f-4b5e-4d02-963d-45adeadc58b8.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0055_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ee8e0a22-437a-494f-848c-04ce4985e574.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_bbc7d9c0-5d29-4dfa-8b21-f2de8ecd5c91.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_611726fb-f4a0-4d95-be29-a830e9d6f55e.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0055_Y_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0054_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_b82fe91e-2bc6-420c-b407-545cfc7efe4d.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b200ef0c-9646-43ec-b12a-5199f3006ec6.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_d83a32ee-0a41-422f-acfa-88614b4f1453.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0054_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0053_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_9ce0e233-6f0a-4004-84ef-0175e8b6242e.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_f521bfe2-65f4-4450-a589-260889b75233.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_3e3ccbce-033f-4d58-98f4-988838a63f0b.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0053_Y_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0050_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b6300787-2048-4b16-a96b-093bc8d70f6f.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b662b965-64b2-404c-b04a-f753be4fbf77.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_3925ba23-3bad-453f-938d-8e940acfbf25.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0050_Y_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0049_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_d4bef765-eaba-4b53-b279-bf74f87e8e06.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_f834ec0d-c1e8-4907-bf29-cb79b6ff1bc1.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_164b038d-ffb9-4fa7-8fed-2744a9df4863.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0049_00001_1__compressed_692481f4-c4c1-41c2-b499-937ca909eea3.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0048_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b2f9e095-6448-4e66-91c1-92285af29b9a.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_10b8ffa3-ca4c-4382-91a2-a42c59153539.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_91fa8be9-f2e7-4d0d-b317-2233047bfbd9.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0048_Y_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0047_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_537c2f9d-a9c6-4bac-a68f-ba6be44e39c1.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_27930177-fd1c-4259-b2a8-63380d89c089.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_b033770c-7b4c-4bfc-b7b0-8736a036aa95.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0047_Y_00001_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0046_Y_00001_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_0820936e-9858-49bc-8f24-089472709368.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_02109916-e569-470a-a5ed-a6b678ea9afd.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_df2bcb0f-e9f0-47e1-abdf-ae4abb63dd82.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0046_Y_00001_1__compressed_bd83dec6-cc48-43a0-b012-473f9f62e0c6.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0045_00000_1__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_e8cb3d63-fb63-4753-a820-aa8271040063.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_7c17b5f3-3cc8-4607-85d3-0848106cc524.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_64bfcf09-4578-496f-bbcd-153433e8857a.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0045_00000_2__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0044-5-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_1afd5fab-2af6-45ce-bfb6-6e2c22054cb1.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b0d0ee2f-f91e-4e50-8183-e65d2ee173dd.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0044-5-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0043-5-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_5a07e14e-30fc-420a-b6a9-00a9c5b084ae.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_e1dc5843-51fc-42bc-b5b5-7ea809a87f99.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_52cfde02-b3ad-4d73-8a9b-60daed2a2c5e.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0043-5-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0042-5-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_184e1faf-16c5-4f8d-8af3-5889a8957764.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_65b7925a-94af-47bd-a656-3d1b445edfd5.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_613252f3-6698-4f77-b5b7-8e5052680433.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0042-5-Y_00001_compressed.jpg"
      ]
    }
  ],
  "necklaces": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0053-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_6ef2cf61-456d-4e2c-95d9-856c88af9c92.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_fcfd04ee-0b51-4b1d-b13e-f9bf435ea252.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_366163f7-f7b6-4dff-a1df-2a36aec1f75e.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0053-Y_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0052_00002_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_684655b2-fad0-4774-8ad6-541f20669531.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_e82806b7-41be-49c8-a863-0aa0480720af.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_6e83046e-ba8e-42ab-8a64-5bc2a9823b1b.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_1a9988dd-1db8-41d7-85d3-d3316af6d5c2.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/SSWNC0337.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/SSWNC0337_1.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/SSWNC0337_1.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/SSWNC0337_2.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/SSWNC0337_3.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_21c7b078-c23a-4b32-945f-c16eb5f655c8.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_21c7b078-c23a-4b32-945f-c16eb5f655c8.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_2b08c885-d711-4330-acd9-b01ea35be882.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_bccdd7c7-ba7b-4f5c-bfe7-185a471d4c5a.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_89758061-f94f-428a-8b00-791a44bdccba.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_a73fe03b-7987-4f5b-a834-e99b122c4ced.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_a73fe03b-7987-4f5b-a834-e99b122c4ced.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_c718e133-1f74-4e2e-8f50-7c8cff8177e3.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_11b2c5e2-e555-4751-9b2e-53e329828e80.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_ea695881-c93f-447e-bd62-90290092ee7b.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_ea695881-c93f-447e-bd62-90290092ee7b.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_78d7c1fb-0ab7-491d-b101-5403a8c1fd3c.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_5b5276e0-d57a-4e7c-9734-b8f46b027674.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_774421bb-6444-4a78-9bcd-f75df25709ca.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_1_1165ebed-75e6-4fec-8da5-c1b9de282bf0.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_1_1165ebed-75e6-4fec-8da5-c1b9de282bf0.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_023e3541-1d2d-4351-9c4b-5f198de9b29c.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_889f99e1-ff2e-40e0-b9b0-b18026a9d139.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_0a44c135-ae9b-4a4d-8652-36d5a29c3b93.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_7f69302a-5e4c-4dee-ac6f-50882fc0bd4a.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_square_7f69302a-5e4c-4dee-ac6f-50882fc0bd4a.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_817e8742-7552-41e5-85c0-46c0a9db828b.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_60b2ae67-08dc-4818-9ec2-ba0304aac68a.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0045-model-2.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_674afaf5-7a4f-4706-9835-8f2b8a333e9b.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0045-S_00000_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0045-S_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0046-S_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2b891c17-d092-4e31-9f3d-65e2f8782025.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0046-S_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0047-model-1.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_09f683fc-f156-419d-8ec6-0a0e210059ee.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0047_00004_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0047-model-2.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0047_00006_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_fef91d20-ee28-42f1-986d-e2ec6c713fe5.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_fef91d20-ee28-42f1-986d-e2ec6c713fe5.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0029-model-1-1.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_81d2c624-6a01-425b-9ad3-54246674e8f4.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0029_S_00000_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0029-model-2.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0029_S_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0028-model-1-2.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_8601af0f-3975-4d9e-8e1f-299544c35845.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0028_00000_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/NKS0028_00002_compressed.jpg"
      ]
    }
  ],
  "earrings": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0143-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_1881dbc5-6c0a-4a0b-b7f4-7ef18a91ea23.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_cc765f96-87c5-44e0-b0b4-7f20d0887a60.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_47ea693f-272d-4b56-9984-8d028d3b40a3.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0143-Y_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0142-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_6fbfbda2-804b-4a5a-a4a2-3b187a90a877.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_9f7f7b71-4de9-4bcf-a8f0-60202dd3546c.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_0a2e5246-35c8-49f5-b1cb-99c9d1dbefed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0142-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0141-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_0f421166-7ed9-4a39-8253-f3929769ec29.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_f639607c-2f50-43b7-ad47-b0f84aa90ea1.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_e929b467-4427-4291-bd9d-781aeb2c2f84.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0141-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0140-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_cf457fb7-6b06-415f-afc9-fb9ab500181e.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_a60244f0-a86d-4665-8c91-1115a61db417.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_9795e374-d78f-4421-a08e-cef9a5e73411.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0140-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0139_Y_00002_2__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_650a45a9-8d9c-4963-8b0c-9879781e821a.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_c239b441-3f1b-488e-a96a-bdf6abc90fd8.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_0bc78d2c-19a0-4756-8d24-90f216b2561f.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0139_Y_00002_3__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0138-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_910f9094-7d3b-4451-a3c4-d9763a913030.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_c36df068-2e2c-4a59-88ff-b50d31a897f9.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_87001c35-a2b7-4300-816e-46f35cd1530a.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0138-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0137-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_e6bc7401-0900-4e8f-b5e2-137fcc8b8fa1.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_affd250d-02f8-4043-a7fc-ccf8b6f5ea3b.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0137-Y_00001_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0137-Y_00002_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0136-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_39bc38ff-cc89-4320-b50b-9b13e473402e.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_fcff802e-6c94-48cc-b943-6143d2116ad9.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_f88d7802-eb41-4f62-be60-863465c8b5ab.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0136-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0135-Y_00000_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_dd5629f8-e056-4027-9512-b815299019a5.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_2cf62d1e-53ef-42a8-8da3-cfc0fa049e45.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_f4fc6e7a-9476-42ac-8219-e5279e558650.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0135-Y_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0134_00002_3__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_da07930d-0f9f-46f9-b6b6-14e872c17af8.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_dea08ed4-b892-4707-8254-0877e0275a42.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_fb853624-e053-4ebf-aeaf-9234b801df1a.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0134_00002_2__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0133_00002_3__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_4bd722e4-7949-4d7f-afa5-4f3fbfa4b49e.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_9103d0f1-5107-4264-9d37-decb228288a1.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_00498edc-7b89-459a-a32f-5c11bb3cd954.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0133_00002_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0132_00002_3__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_2a11899f-2391-4744-936c-88e6386f4d06.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_060b19ec-9e16-48af-a85e-42efc5a290ab.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ccaa66b7-3a1c-4380-a0b4-729704f0baf5.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0132_00002_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0131_00002_3__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_cbc803a5-eaf7-4ca9-9cdb-f02c1b4fa8c1.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_ccd9fe80-2748-48c2-b8d9-636d896776c2.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_3ac62886-2de1-45bd-b6e1-1be128142a6a.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0131_00002_1__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0130_00002_compressed_3.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_c3d3e238-e124-4c29-9299-99d6342b4acb.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_a6cb791d-c22e-4bf2-8a23-99ce8aed6bba.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_a038a568-0cb2-46ae-aed4-7f51c3ca5332.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/ERS0130_00002_compressed_1.jpg"
      ]
    }
  ],
  "bracelets": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR117_174470cc-f04c-430f-bf6c-b2ead1725734.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR1172_62d62419-2cf6-438b-b28e-7e760984e755.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR1172_62d62419-2cf6-438b-b28e-7e760984e755.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/GoldBeadedBracelet_1_cdb81e71-5dc0-4bc8-a17c-05468ae5271d.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR1173_df3c3843-ace8-4608-9d96-51f1b7819c18.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR082-G.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR082G_b46fb340-0ab1-40ea-9c81-49398671c630.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR082G_b46fb340-0ab1-40ea-9c81-49398671c630.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR082G-3_01c85d5d-c5dd-49e7-845b-2572a8bacf01.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR082G-2_52ac3d95-f7be-45f5-b20b-0162d41cb808.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/MB9YG0024.png",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/MB9YG0024_3.png",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/MB9YG0024_3.png",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/MB9YG0024_4.png",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/MB9YG0024_1.png"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0006_Y_00000_1__compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0006_Y_00000_3__compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR9YG0019_05_Y_1.png",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR9YG0019-model-2_compressed.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR9YG0019-model-2_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR9YG0019_Size_1.png",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR9YG0019-model-1_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0002_S_00003_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_df7cfed9-23a5-4a6e-8cd2-90c187431442.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0002_S_00002_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0002_S_00005_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0002_S_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0004_S_00003_compressed.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_9cd38d48-caa6-43ed-ae3d-0059ad58f157.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0004_S_00005_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0004_S_00002_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BRS0004_S_00001_compressed.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_20_4b86556a-695d-41ca-a284-d68fc97b4ced.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_20_4b86556a-695d-41ca-a284-d68fc97b4ced.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_11_a708542b-3240-4dea-a95f-a9d49fc4fdd0.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_11_a708542b-3240-4dea-a95f-a9d49fc4fdd0.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify2_5a50ed03-1e1d-439c-9318-6af606c15be7.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify2_5a50ed03-1e1d-439c-9318-6af606c15be7.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR0432.webp",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/model-1-BR0432.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/model-1-BR0432.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopifycopy1_1_d3eb7e84-1602-4c7c-bd03-b71d9393aefd.webp",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopifycopy_1_92b79427-b10b-4633-82dd-3938ffeffc74.webp"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_ada249bd-3d87-4533-a6bd-d51e7c2d09d2.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_ada249bd-3d87-4533-a6bd-d51e7c2d09d2.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_148d2449-5215-4f20-98da-0d277ffd61de.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_148d2449-5215-4f20-98da-0d277ffd61de.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_62fa6808-5845-4222-b8e0-8f76b9ce95a9.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_62fa6808-5845-4222-b8e0-8f76b9ce95a9.jpg",
      "extra": []
    }
  ],
  "bangles": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR068-WB.png",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR068-WB.png",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_14_f36165cb-055f-4119-a392-6ff18cbc1838.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_14_f36165cb-055f-4119-a392-6ff18cbc1838.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_8f38bdde-be7a-439b-90d8-7914931e7e70.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_8f38bdde-be7a-439b-90d8-7914931e7e70.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_12_2d458364-f93e-4cec-a41b-ce2896e179ff.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_12_2d458364-f93e-4cec-a41b-ce2896e179ff.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_10_9d57bf5c-e7fd-42f9-99a8-5fd843f4a9d8.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_10_9d57bf5c-e7fd-42f9-99a8-5fd843f4a9d8.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_9_90fe73bf-3064-4070-b341-de5d1f36b237.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_9_90fe73bf-3064-4070-b341-de5d1f36b237.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_8_196872bc-8023-44d1-abdb-24484ad0bd44.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_8_196872bc-8023-44d1-abdb-24484ad0bd44.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_6_2daf0284-11fd-46ef-a464-479976bcdf32.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_6_2daf0284-11fd-46ef-a464-479976bcdf32.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_4_befdcac6-2fe8-4c46-b9f2-f8806c51141f.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_4_befdcac6-2fe8-4c46-b9f2-f8806c51141f.jpg",
      "extra": []
    }
  ],
  "charms": [
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR080-RG-1_4d0dcd79-a69c-49d7-b750-3f037687f70f.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_ae49997b-8559-4058-ae43-c576566fed86.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_37e50013-541e-4618-b82a-86ead1449b33.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR080-RG-2_ab5bb67f-5321-45a2-8130-c3344908288c.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/BR080-RG-ML2_ed531c5f-d961-4db4-b738-b6f2c0c50618.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0036-model-1-1.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_c2294f50-aa68-4828-a787-9ddd52412666.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0036-S_00001_compressed.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/RGS0036-model-2.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_d4784a46-9ee7-4b28-b15c-d3f133e00606.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_d4784a46-9ee7-4b28-b15c-d3f133e00606.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_040de813-e7b6-4310-9691-d08b6b8d4d3a.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_040de813-e7b6-4310-9691-d08b6b8d4d3a.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_0c050ee8-fe10-4306-8407-a300770d5861.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_01f9f581-0fc6-4598-b36b-fe3d6884553d.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_3f738891-164a-4714-aeae-bde5a2ed0954.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2f95d09e-39e0-49b4-a686-9e3d3c83f5a2.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2f95d09e-39e0-49b4-a686-9e3d3c83f5a2.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_71799c52-7b79-4e82-8620-77e00f438667.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_71799c52-7b79-4e82-8620-77e00f438667.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_828e630f-3123-4b7d-889d-81aabbae3670.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_828e630f-3123-4b7d-889d-81aabbae3670.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_b84240bc-5669-416f-abc8-0e44c0970326.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_b84240bc-5669-416f-abc8-0e44c0970326.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_5e062cf2-74ce-463d-b77e-59b7ecbe1a7b.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_e227e4ff-b88d-4a6f-ac84-4b7e8625d427.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_2ff0cc64-d697-4576-998a-562cd42e33ae.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1f5e82ae-f1db-4bdf-b703-38ceccb9b2c7.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1f5e82ae-f1db-4bdf-b703-38ceccb9b2c7.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_a9a4b770-efec-4e5c-8ff0-9adde896358b.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_a9a4b770-efec-4e5c-8ff0-9adde896358b.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_85b51cbe-663e-4ef1-ab65-629cda693cd4.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_85b51cbe-663e-4ef1-ab65-629cda693cd4.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_26c2ee9e-7748-4491-bdda-b89103969396.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_86bd8b49-5c2c-4eb4-9335-19240e9e02e3.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_2252efb9-68ce-49de-92ca-6692fdaa88b8.jpg"
      ]
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_c156062f-c7e1-4bd4-8051-3f748a48aebd.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_c156062f-c7e1-4bd4-8051-3f748a48aebd.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_91beb88c-2ca2-431a-886e-0f0f286988a6.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_91beb88c-2ca2-431a-886e-0f0f286988a6.jpg",
      "extra": []
    },
    {
      "primary": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_a3d12bb7-d3b8-4208-8dbb-3c5f4c847bc4.jpg",
      "hover": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_a3d12bb7-d3b8-4208-8dbb-3c5f4c847bc4.jpg",
      "extra": [
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_1ad5d37f-bb2a-4362-adda-e85e5f61e681.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_7acd5996-92de-44ef-b1b3-166e5848d5f0.jpg",
        "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_3d206b62-1181-458e-ab17-6c68afe2a103.jpg"
      ]
    }
  ]
};

export const BANNERS = {
  "hero": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_76039358-ad26-4547-9060-1aff85ac34c6.jpg",
  "signature": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_7b905e74-6e4b-4f39-b99e-d0b971c55e19.jpg",
  "craft": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ba08e1de-5486-44e9-8a71-2585f8d52771.jpg",
  "story": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_121eaebb-131c-49e9-b628-11e9dbdb16d3.jpg",
  "personalisation": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b0ed2fe1-e228-4c8e-b3da-8f47e15c12c6.jpg",
  "collection": "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_a26ef832-ea5a-4ead-adf8-fe96f3d0e660.jpg"
} as const;

export const ALL_BANNERS: string[] = [
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_76039358-ad26-4547-9060-1aff85ac34c6.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_7b905e74-6e4b-4f39-b99e-d0b971c55e19.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ba08e1de-5486-44e9-8a71-2585f8d52771.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_121eaebb-131c-49e9-b628-11e9dbdb16d3.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b0ed2fe1-e228-4c8e-b3da-8f47e15c12c6.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_a26ef832-ea5a-4ead-adf8-fe96f3d0e660.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_ee8e0a22-437a-494f-848c-04ce4985e574.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_bbc7d9c0-5d29-4dfa-8b21-f2de8ecd5c91.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_611726fb-f4a0-4d95-be29-a830e9d6f55e.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_b82fe91e-2bc6-420c-b407-545cfc7efe4d.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b200ef0c-9646-43ec-b12a-5199f3006ec6.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_d83a32ee-0a41-422f-acfa-88614b4f1453.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_9ce0e233-6f0a-4004-84ef-0175e8b6242e.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_f521bfe2-65f4-4450-a589-260889b75233.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_3e3ccbce-033f-4d58-98f4-988838a63f0b.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b6300787-2048-4b16-a96b-093bc8d70f6f.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b662b965-64b2-404c-b04a-f753be4fbf77.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_3925ba23-3bad-453f-938d-8e940acfbf25.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_d4bef765-eaba-4b53-b279-bf74f87e8e06.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_f834ec0d-c1e8-4907-bf29-cb79b6ff1bc1.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_164b038d-ffb9-4fa7-8fed-2744a9df4863.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_b2f9e095-6448-4e66-91c1-92285af29b9a.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_10b8ffa3-ca4c-4382-91a2-a42c59153539.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_91fa8be9-f2e7-4d0d-b317-2233047bfbd9.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_537c2f9d-a9c6-4bac-a68f-ba6be44e39c1.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_27930177-fd1c-4259-b2a8-63380d89c089.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_b033770c-7b4c-4bfc-b7b0-8736a036aa95.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_0820936e-9858-49bc-8f24-089472709368.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_02109916-e569-470a-a5ed-a6b678ea9afd.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_df2bcb0f-e9f0-47e1-abdf-ae4abb63dd82.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_e8cb3d63-fb63-4753-a820-aa8271040063.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_7c17b5f3-3cc8-4607-85d3-0848106cc524.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_64bfcf09-4578-496f-bbcd-153433e8857a.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_1afd5fab-2af6-45ce-bfb6-6e2c22054cb1.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_b0d0ee2f-f91e-4e50-8183-e65d2ee173dd.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_5a07e14e-30fc-420a-b6a9-00a9c5b084ae.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_e1dc5843-51fc-42bc-b5b5-7ea809a87f99.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_2_compressed_52cfde02-b3ad-4d73-8a9b-60daed2a2c5e.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_1_compressed_184e1faf-16c5-4f8d-8af3-5889a8957764.jpg",
  "https://cdn.shopify.com/s/files/1/0613/1400/7297/files/Shopify_3_compressed_65b7925a-94af-47bd-a656-3d1b445edfd5.jpg"
];
